[app]
primary_region = "sea"

[build]

[env]
  OPENAI_API_KEY = "${OPENAI_API_KEY}"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "get"
  path = "/healthz"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
